### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by streetburner** [darknethaxor/DH-HackBar#1]
java.lang.IndexOutOfBoundsException: Index: 704, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.darknethaxor.hackbar.w.getView(Unknown Source)
	at android.widget.AbsListView.obtainView(AbsListView.java:2497)
	at android.widget.ListView.makeAndAddView(ListView.java:2012)
	at android.widget.ListView.fillDown(ListView.java:721)
	at android.widget.ListView.fillGap(ListView.java:685)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5783)
	at android.widget.ListView.trackMotionScroll(ListView.java:1931)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:5279)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:910)
	at android.view.Choreographer.doCallbacks(Choreographer.java:712)
	at android.view.Choreographer.doFrame(Choreographer.java:643)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:896)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6339)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by darknethaxor** [comment]
We have worked on that bug already. And, we have fixed it. We hope that, in our next update, you won't face this problem ever. 😊
