### ISSUE TITLE
When find admin panel

### ISSUE THREAD

**Issue by baradatipu** [darknethaxor/DH-HackBar#15]
Realme RMX3360, Android 12, V1.1;

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.darknethaxor.hackbar.w.getCount(Unknown Source:2)
	at android.widget.ListView.setAdapter(ListView.java:581)
	at com.darknethaxor.hackbar.aa.b(Unknown Source:49)
	at com.darknethaxor.hackbar.aa.a(Unknown Source:0)
	at com.darknethaxor.hackbar.aa.onCancelled(Unknown Source:2)
	at android.os.AsyncTask.finish(AsyncTask.java:769)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8184)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by AbilashN123** [comment]
Mk
