### ISSUE TITLE
Cresh dh hackbar 

### ISSUE THREAD

**Issue by Amurharsha07** [darknethaxor/DH-HackBar#32]
![Screenshot_20231202-215232](https://github.com/darknethaxor/DH-HackBar/assets/150145508/7f82ce19-6eed-4504-894d-fb0244ef8452)

Cresh dh hackbar

**Comment by Amurharsha07** [comment]
Cresh dh hackbar

**Comment by Usman0220** [comment]
Same
INFINIX MOBILITY LIMITED Infinix X663, Android 12, V1.1;

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.darknethaxor.hackbar.w.getCount(Unknown Source:2)
	at android.widget.ListView.setAdapter(ListView.java:581)
	at com.darknethaxor.hackbar.aa.b(Unknown Source:49)
	at com.darknethaxor.hackbar.aa.a(Unknown Source:0)
	at com.darknethaxor.hackbar.aa.onCancelled(Unknown Source:2)
	at android.os.AsyncTask.finish(AsyncTask.java:769)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:342)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
