### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by immaghzbad** [darknethaxor/DH-HackBar#42]
Xiaomi 2201116PG, Android 13, V1.1;

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.darknethaxor.hackbar/com.darknethaxor.hackbar.QueryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.darknethaxor.hackbar.QueryActivity.a(Unknown Source:309)
	at com.darknethaxor.hackbar.QueryActivity.onCreate(Unknown Source:11)
	at android.app.Activity.performCreate(Activity.java:8540)
	at android.app.Activity.performCreate(Activity.java:8504)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
	... 12 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.darknethaxor.hackbar.QueryActivity.a(Unknown Source:309)
	at com.darknethaxor.hackbar.QueryActivity.onCreate(Unknown Source:11)
	at android.app.Activity.performCreate(Activity.java:8540)
	at android.app.Activity.performCreate(Activity.java:8504)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by Ahmedjutt751** [comment]
That’s good bro

**Comment by Riyazkhan09** [comment]
This problem all device xiaomi 👍
