### ISSUE TITLE
It get crashed when we try to download something

### ISSUE THREAD

**Issue by tausifzaman** [darknethaxor/DH-HackBar#49]
Samsung SM-*******, Android 13, V1.1;

java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://shrisairugnalay.in/0194232e-9cab-476f-ba7b-8ee0c54149f6
	at android.app.DownloadManager$Request.<init>(DownloadManager.java:634)
	at com.darknethaxor.hackbar.fu.onClick(Unknown Source:8)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:188)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by frozenflame00001** [comment]
We have discontinued our work on this project so, there will be no update and no request will be accepted for now. If in future we agree upon to work on this project, you will be notified by our Facebook page " [DH Hackbar](https://www.facebook.com/share/1CU22YeZRX/) ".
