### ISSUE TITLE
Admin finder error when i was stop

### ISSUE THREAD

**Issue by RizeKishimaro** [darknethaxor/DH-HackBar#9]
![Screenshot_2021-11-03-08-24-18-56](https://user-images.githubusercontent.com/75617768/140000107-48106b04-0bad-465b-bc5a-91f9c7ecf914.png)

**Comment by YeMinAung2004** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.darknethaxor.hackbar.w.getCount(Unknown Source)
	at android.widget.ListView.setAdapter(ListView.java:515)
	at com.darknethaxor.hackbar.aa.b(Unknown Source)
	at com.darknethaxor.hackbar.aa.a(Unknown Source)
	at com.darknethaxor.hackbar.aa.onCancelled(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java:665)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:232)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by dk1285** [comment]
Same
